# -*- coding: utf-8 -*-
"""AI-assignment group 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDZXN5o9QO5SGtm3jLwSLDccfByl7pa_
"""

import pandas as pd
dataset=pd.read_csv('Book11.csv')
print(dataset)

!pip install haversine
from haversine import haversine
distance=[]
i=0
j=1
while i<len(dataset):
    while j<len(dataset):
        c1=(dataset.iloc[i,1],dataset.iloc[i,2])
        c2=(dataset.iloc[j,1],dataset.iloc[j,2])
        distance.append(haversine(c1,c2))
        j+=1
    i+=1


print(distance)
search_graph={ }
i=0
while i<len(dataset):
    for j in distance:
        search_graph[dataset.iloc[i,0]]=[j, dataset.iloc[i,1],dataset.iloc[i,2],dataset.iloc[i,0]]
    i+=1
print(search_graph)

new_graph={}

i=0
while i < len(dataset):
    location_i_name = dataset.iloc[i,0]

    j=0
    while j < len(dataset):

        if i != j:
            location_j_name = dataset.iloc[j,0]

            if location_i_name in search_graph and location_j_name in search_graph:

                new_graph[(location_i_name, location_j_name)] = (search_graph[location_i_name], search_graph[location_j_name])
        j+=1
    i+=1

print(new_graph)